language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.1.0
    - android-16
    - android-26
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
